version: "3"
services:

  db:
    image: postgres:9.6
    container_name: wowfood-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/Projects/DockerCache/WowFood/:/var/lib/postgresql/data